# Atividade Prática - Exercício 3
#### Valor : 10 pontos

1) Solicite ao usuário que informe a quantidade de linhas (n) e colunas (m) e crie um ndarray nxm com valores aleatórios.

In [ ]:
!pip install numpy

In [ ]:
import numpy as np

In [ ]:
n = int(input("Digite o numero de linhas: "))
m = int(input('Digite o numero de colunas: '))
total = n*m
vet = np.ndarray((n,m),dtype = int)
print(vet)


Digite o numero de linhas: 3
Digite o numero de colunas: 4
[[    51155040 137438953588 137438953533 481036337262]
 [472446402606 416611827812 489626271858 519691042913]
 [472446402600 468151435308           41            0]]


2) Retorne a média dos valores de cada uma das n linhas

In [ ]:
from numpy.core.fromnumeric import mean
for i in range(0,n):
  media = mean(vet[i])
  print(f"Media da linha {i} -",media)


Media da linha 0 - 188991349855.75
Media da linha 1 - 474593886297.25
Media da linha 2 - 235149459487.25


3) Retorne a mediana dos valores das m colunas

In [ ]:
from numpy.lib.function_base import median
for i in range(0,m):
  mediana = median(vet[::,i])
  print(f"Mediana da coluna {i} -",mediana)

Mediana da coluna 0 - 472446402600.0
Mediana da coluna 1 - 416611827812.0
Mediana da coluna 2 - 137438953533.0
Mediana da coluna 3 - 481036337262.0


4)  Dados os seguintes arrays x e y, calcula a correlação entre eles.

In [ ]:
import numpy as np
x = np.array([0, 1, 3, 8, -3])
y = np.array([5, 4, 2, 1, 7])
z = np.array([-5, -41, -97])

In [ ]:
np.corrcoef(x, y)

array([[ 1.        , -0.95320714],
       [-0.95320714,  1.        ]])

5) Faça uma função que receba um ndarray de valores inteiros e retorne um ndarray de mesma dimensão, onde os valores negativos serão substituídos por True e os valores positivos por False.

In [ ]:
def noNeg(vet):
  for i in range(0,2):
    for j in range(0,3):
      if vet[i,j]<0:
        vet[i,j] = True
      else:
        vet[i,j] = False
  return vet

vet = np.random.randn(6).reshape(2,3)
print(vet)
noNeg(vet)


[[-2.18337133 -0.598444    1.46575933]
 [ 0.85967808  0.81823582 -1.49904966]]


array([[1., 1., 0.],
       [0., 0., 1.]])