In [2]:
!pip install numpy

In [2]:
import numpy as np

In [3]:
import numpy as np
vet = np.array([1,2,3,4])
print(vet)

[1 2 3 4]


In [4]:
import numpy as np
vet = np.array([1,2,3,4,5,6], dtype = 'float64')
print(vet)

[1. 2. 3. 4. 5. 6.]


In [5]:
print(vet.dtype)

float64


In [6]:
print(vet.shape)

(6,)


In [7]:
vet = vet.reshape(2,3)

In [8]:
vet

array([[1., 2., 3.],
       [4., 5., 6.]])

In [9]:
vet2 = np.array([1,4,2,4,566,3,2,2,4,54,2,2])
vet2 = vet2.reshape(3,-1) #-1 quando nao se sabe o numero ao certo
vet2

array([[  1,   4,   2,   4],
       [566,   3,   2,   2],
       [  4,  54,   2,   2]])

In [10]:
#axis 0 = linhas
#axis 1 = colunas
#vet2 = sum(axis = 0)

In [11]:
somatorio = 0
for valor in vet2:
    somatorio += valor
print(somatorio)

[571  61   6   8]


In [12]:
vet2 = vet2.reshape(-1)
vet2

array([  1,   4,   2,   4, 566,   3,   2,   2,   4,  54,   2,   2])

In [16]:
aleatorio = np.random.random((5))
aleatorio

array([0.91625079, 0.92714984, 0.09706017, 0.50755637, 0.27364944])

In [27]:
v = np.arange(100)
v

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [29]:
#u = v[1:3]
print(v[50:70])

[50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69]


In [34]:
print(v[0])

0


In [35]:
v = v.reshape(2,-1)

In [36]:
v

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98, 99]])

In [40]:
print(v[1,3])

53


In [44]:
print(v[:,[2,4]])

[[ 2  4]
 [52 54]]


In [41]:
u = np.arange(9)
u

array([0, 1, 2, 3, 4])

In [42]:
print(u[[0,3]])

[0 3]


In [46]:
x = np.arange(9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [52]:
print(x[0],x[1],x[2])

[0 1 2] [3 4 5] [6 7 8]


In [54]:
print(x[0,0],x[1,0],x[0,2])

0 3 2


In [61]:
print(x[::,0])

[0 3 6]


In [64]:
print(x[1:2])
print(x[1:2,2])

[[3 4 5]]
[5]


In [65]:
t = np.arange(0,10,0.5)
t

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [66]:
y = np.linspace(0,10,40)
y

array([ 0.        ,  0.25641026,  0.51282051,  0.76923077,  1.02564103,
        1.28205128,  1.53846154,  1.79487179,  2.05128205,  2.30769231,
        2.56410256,  2.82051282,  3.07692308,  3.33333333,  3.58974359,
        3.84615385,  4.1025641 ,  4.35897436,  4.61538462,  4.87179487,
        5.12820513,  5.38461538,  5.64102564,  5.8974359 ,  6.15384615,
        6.41025641,  6.66666667,  6.92307692,  7.17948718,  7.43589744,
        7.69230769,  7.94871795,  8.20512821,  8.46153846,  8.71794872,
        8.97435897,  9.23076923,  9.48717949,  9.74358974, 10.        ])

In [70]:
soma = y[1]+y[-2]
print(soma)

10.0


In [72]:
x = np.random.randn(3,8)
x

array([[ 1.39266374,  0.53510406, -0.28472464,  0.74494028,  0.58674765,
         0.29667108,  0.67136221, -0.63154129],
       [ 0.58679512, -2.13909671, -0.52020321,  1.92304048,  0.7559027 ,
        -2.09946167,  0.96131435, -0.1316656 ],
       [-0.00519529,  0.69643631,  0.82385534, -1.61733069, -0.24472501,
        -0.18270737, -0.5329676 ,  0.78316524]])

In [8]:
lista44 = np.array([3094, 3268, 4302, 3184, 3266, 3124, 3316, 3212, 3380, 3018])
print('Media:',np.mean(lista44))
print('Mediana:',np.median(lista44))
print('Desvio Padrao:',np.std(lista44))

Media: 3316.4
Mediana: 3239.0
Desvio Padrao: 344.1346248199969


In [3]:
lista99 = np.array([76,34,64,74,42,23,59,79,26,86])
print('Media:',np.mean(lista99))
print('Mediana:',np.median(lista99))
print('Desvio Padrao:',np.std(lista99))

Media: 56.3
Mediana: 61.5
Desvio Padrao: 22.122612865572638
